"6.topic: agda":
  - doc/languages-frameworks/agda.section.md
  - botnix/tests/agda.nix
  - pkgs/build-support/agda/**/*
  - pkgs/development/libraries/agda/**/*
  - pkgs/top-level/agda-packages.nix

"6.topic: cinnamon":
  - pkgs/desktops/cinnamon/**/*
  - botnix/modules/services/x11/desktop-managers/cinnamon.nix
  - botnix/tests/cinnamon.nix

"6.topic: emacs":
  - botnix/modules/services/editors/emacs.nix
  - botnix/modules/services/editors/emacs.xml
  - botnix/tests/emacs-daemon.nix
  - pkgs/applications/editors/emacs/elisp-packages/**/*
  - pkgs/applications/editors/emacs/**/*
  - pkgs/build-support/emacs/**/*
  - pkgs/top-level/emacs-packages.nix

"6.topic: Enlightenment DE":
  - botnix/modules/services/x11/desktop-managers/enlightenment.nix
  - pkgs/desktops/enlightenment/**/*
  - pkgs/development/python-modules/python-efl/*

"6.topic: erlang":
  - doc/languages-frameworks/beam.section.md
  - pkgs/development/beam-modules/**/*
  - pkgs/development/interpreters/elixir/**/*
  - pkgs/development/interpreters/erlang/**/*
  - pkgs/development/tools/build-managers/rebar/**/*
  - pkgs/development/tools/build-managers/rebar3/**/*
  - pkgs/development/tools/erlang/**/*
  - pkgs/top-level/beam-packages.nix

"6.topic: fetch":
  - pkgs/build-support/fetch*/**/*

"6.topic: flakes":
  - "**/flake.nix"
  - lib/systems/flake-systems.nix
  - botnix/modules/config/nix-flakes.nix

"6.topic: GNOME":
  - doc/languages-frameworks/gnome.section.md
  - botnix/modules/services/desktops/gnome/**/*
  - botnix/modules/services/x11/desktop-managers/gnome.nix
  - botnix/tests/gnome-xorg.nix
  - botnix/tests/gnome.nix
  - pkgs/desktops/gnome/**/*

"6.topic: golang":
  - doc/languages-frameworks/go.section.md
  - pkgs/build-support/go/**/*
  - pkgs/development/compilers/go/**/*

"6.topic: haskell":
  - doc/languages-frameworks/haskell.section.md
  - maintainers/scripts/haskell/**/*
  - pkgs/development/compilers/ghc/**/*
  - pkgs/development/haskell-modules/**/*
  - pkgs/development/tools/haskell/**/*
  - pkgs/test/haskell/**/*
  - pkgs/top-level/haskell-packages.nix
  - pkgs/top-level/release-haskell.nix

"6.topic: jupyter":
  - pkgs/development/python-modules/jupyter*/**/*
  - pkgs/development/python-modules/mkdocs-jupyter/*
  - botnix/modules/services/development/jupyter/**/*
  - pkgs/applications/editors/jupyter-kernels/**/*
  - pkgs/applications/editors/jupyter/**/*

"6.topic: kernel":
  - pkgs/build-support/kernel/**/*
  - pkgs/os-specific/linux/kernel/**/*

"6.topic: lib":
  - lib/**

"6.topic: lua":
  - pkgs/development/interpreters/lua-5/**/*
  - pkgs/development/interpreters/luajit/**/*
  - pkgs/development/lua-modules/**/*
  - pkgs/top-level/lua-packages.nix

"6.topic: Lumina DE":
  - botnix/modules/services/x11/desktop-managers/lumina.nix
  - pkgs/desktops/lumina/**/*

"6.topic: LXQt":
  - botnix/modules/services/x11/desktop-managers/lxqt.nix
  - pkgs/desktops/lxqt/**/*

"6.topic: mate":
  - botnix/modules/services/x11/desktop-managers/mate.nix
  - botnix/tests/mate.nix
  - pkgs/desktops/mate/**/*

"6.topic: module system":
  - lib/modules.nix
  - lib/types.nix
  - lib/options.nix
  - lib/tests/modules.sh
  - lib/tests/modules/**

"6.topic: botnix":
  - botnix/**/*
  - pkgs/os-specific/linux/botnix-rebuild/**/*

"6.topic: nim":
  - doc/languages-frameworks/nim.section.md
  - pkgs/development/compilers/nim/*
  - pkgs/development/nim-packages/**/*
  - pkgs/top-level/nim-packages.nix

"6.topic: nodejs":
  - doc/languages-frameworks/javascript.section.md
  - pkgs/build-support/node/**/*
  - pkgs/development/node-packages/**/*
  - pkgs/development/tools/yarn/*
  - pkgs/development/tools/yarn2nix-moretea/**/*
  - pkgs/development/web/nodejs/*

"6.topic: ocaml":
  - doc/languages-frameworks/ocaml.section.md
  - pkgs/development/compilers/ocaml/**/*
  - pkgs/development/compilers/reason/**/*
  - pkgs/development/ocaml-modules/**/*
  - pkgs/development/tools/ocaml/**/*
  - pkgs/top-level/ocaml-packages.nix

"6.topic: pantheon":
  - botnix/modules/services/desktops/pantheon/**/*
  - botnix/modules/services/x11/desktop-managers/pantheon.nix
  - botnix/modules/services/x11/display-managers/lightdm-greeters/pantheon.nix
  - botnix/tests/pantheon.nix
  - pkgs/desktops/pantheon/**/*

"6.topic: policy discussion":
  - .github/**/*

"6.topic: printing":
  - botnix/modules/services/printing/cupsd.nix
  - pkgs/misc/cups/**/*

"6.topic: python":
  - doc/languages-frameworks/python.section.md
  - pkgs/development/interpreters/python/**/*
  - pkgs/development/python-modules/**/*
  - pkgs/top-level/python-packages.nix

"6.topic: qt/kde":
  - doc/languages-frameworks/qt.section.md
  - botnix/modules/services/x11/desktop-managers/plasma5.nix
  - botnix/tests/plasma5.nix
  - pkgs/applications/kde/**/*
  - pkgs/desktops/plasma-5/**/*
  - pkgs/development/libraries/kde-frameworks/**/*
  - pkgs/development/libraries/qt-5/**/*

"6.topic: ruby":
  - doc/languages-frameworks/ruby.section.md
  - pkgs/development/interpreters/ruby/**/*
  - pkgs/development/ruby-modules/**/*

"6.topic: rust":
  - doc/languages-frameworks/rust.section.md
  - pkgs/build-support/rust/**/*
  - pkgs/development/compilers/rust/**/*

"6.topic: stdenv":
  - pkgs/stdenv/**/*

"6.topic: steam":
  - pkgs/games/steam/**/*

"6.topic: systemd":
  - pkgs/os-specific/linux/systemd/**/*
  - botnix/modules/system/boot/systemd*/**/*

"6.topic: TeX":
  - doc/languages-frameworks/texlive.section.md
  - pkgs/test/texlive/**
  - pkgs/tools/typesetting/tex/**/*

"6.topic: vim":
  - doc/languages-frameworks/vim.section.md
  - pkgs/applications/editors/vim/**/*
  - pkgs/applications/editors/vim/plugins/**/*
  - botnix/modules/programs/neovim.nix
  - pkgs/applications/editors/neovim/**/*

"6.topic: vscode":
  - pkgs/applications/editors/vscode/**/*

"6.topic: xfce":
  - botnix/doc/manual/configuration/xfce.xml
  - botnix/modules/services/x11/desktop-managers/xfce.nix
  - botnix/tests/xfce.nix
  - pkgs/desktops/xfce/**/*

"6.topic: zig":
  - pkgs/development/compilers/zig/**/*
  - doc/hooks/zig.section.md

"8.has: changelog":
  - botnix/doc/manual/release-notes/**/*

"8.has: documentation":
  - doc/**/*
  - botnix/doc/**/*

"8.has: module (update)":
  - botnix/modules/**/*
