name: "No channel PR"

on:
  pull_request:
    branches:
      - 'botnix-**'
      - 'nixpkgs-**'

permissions:
  contents: read

jobs:
  fail:
    permissions:
      contents: none
    name: "This PR is is targeting a channel branch"
    runs-on: ubuntu-latest
    steps:
    - run: |
        cat <<EOF
        The botnix-* and nixpkgs-* branches are pushed to by the channel
        release script and should not be merged into directly.

        Please target the equivalent release-* branch or master instead.
        EOF
        exit 1
